# Train on NH-Haze for Ablation Studies

SCHEDULE:
  - RESOLUTION: 256 
    EPOCHS: 200
    BATCH_SIZE: 4

    
SCHEDULER:
    TYPE: Cosine
    WARMUP_EPOCHS: 20
    # TYPE: Fixed
    
OPTIM:
    LR: 0.0001
    # LR: 0.00005

LOSS:
    # Physics Arrangement
    W_PHYS: 0.0
    # Keep small TV—it helps edges without strong physics
    W_TV: 0.00
    W_ATM: 0.00 

    W_FLOW: 1.0
    W_PERC: 0.2
    
    W_FFT: 0.05
    W_CR: 0.1
    W_SSIM: 0.2
    DENSITY_BOOST: 5.0

    

TRAIN:
    STEPS_PER_EPOCH: 100
    PATIENCE: 50

EVAL:
    METRIC_EARLY_STOPPING: SSIM