SCHEDULE:
  - RESOLUTION: 256 
    EPOCHS: 150
    BATCH_SIZE: 16

  # - RESOLUTION: 512 
  #   EPOCHS: 5
  #   BATCH_SIZE: 8
    
SCHEDULER:
    TYPE: Cosine
    WARMUP_EPOCHS: 10
    # TYPE: Fixed
    
OPTIM:
    LR: 0.0002
    # LR: 0.00005

LOSS:
    W_FLOW: 1.0
    W_PERC: 0.2
    W_PHYS: 0.2
    W_TV: 0.01
    W_ATM: 0.01 
    W_FFT: 0.01 
    DENSITY_BOOST: 3.5

EVAL:
    METRIC_EARLY_STOPPING: PSNR