SCHEDULE:
#  - RESOLUTION: 128 
#    EPOCHS: 30
#    BATCH_SIZE: 64 
#    PATIENCE: 6 

#  - RESOLUTION: 256 
#    EPOCHS: 30 
#    BATCH_SIZE: 16 
#    PATIENCE: 6 

  - RESOLUTION: 512 
    EPOCHS: 30
    BATCH_SIZE: 64 
    PATIENCE: 8
