SCHEDULE:
  - RESOLUTION: 256 
    EPOCHS: 300
    BATCH_SIZE: 8

    
SCHEDULER:
    TYPE: Cosine
    WARMUP_EPOCHS: 30
    # TYPE: Fixed
    
OPTIM:
    LR: 0.0002
    # LR: 0.00005

LOSS:
    W_PHYS: 0.2
    W_TV: 0.01
    W_ATM: 0.00 
    
    W_PERC: 0.2
    W_CR: 0.1
    
    W_FFT: 0.05
    W_SSIM: 0.2
    
    DENSITY_BOOST: 5.0

    W_FLOW: 1.0

TRAIN:
    STEPS_PER_EPOCH: 200
    PATIENCE: 50

EVAL:
    METRIC_EARLY_STOPPING: SSIM