SCHEDULE:
  - RESOLUTION: 128 
    EPOCHS: 40
    BATCH_SIZE: 128 
    PATIENCE: 4  
    EVAL_INTERVAL: 5

  - RESOLUTION: 256 
    EPOCHS: 50 
    BATCH_SIZE: 64 
    PATIENCE: 5 
    EVAL_INTERVAL: 5

  - RESOLUTION: 512 
    EPOCHS: 10
    BATCH_SIZE: 16 
    PATIENCE: 4
    EVAL_INTERVAL: 1
