SCHEDULE:
  - RESOLUTION: 256 
    EPOCHS: 300
    BATCH_SIZE: 4

  # - RESOLUTION: 512 
  #   EPOCHS: 5
  #   BATCH_SIZE: 8
    
SCHEDULER:
    TYPE: Cosine
    WARMUP_EPOCHS: 30
    # TYPE: Fixed
    
OPTIM:
    LR: 0.0002
    # LR: 0.00005

LOSS:
    W_FLOW: 1.0
    W_PERC: 0.2
    W_PHYS: 0.2
    W_TV: 0.01
    W_ATM: 0.00 
    W_FFT: 0.05
    DENSITY_BOOST: 10.0

TRAIN:
    STEPS_PER_EPOCH: 200
    PATIENCE: 50

EVAL:
    METRIC_EARLY_STOPPING: SSIM